language: python
python:
  - "3.9"
  - "3.11"
cache: pip
before_install:
  - python3 --version
  - pip3 install -U pip
  - pip install ".[dev]"
script:
  - ruff check .
  - mypy
  - python3 -m pytest --cov=rna_draw
