"""Type stub for the compiled `rna_draw._layout_core` pybind11 extension.

The extension itself is built by `src/layout_core/bindings.cpp`
(CMakeLists.txt) and installed alongside this package; it is not part of
the source tree, so mypy needs this stub to type-check callers.
"""

def plot_coords_turtle(structure: str) -> tuple[list[float], list[float]]: ...
def dump_turtle(structure: str) -> tuple[list[float], list[float]]: ...
def dump_tree(
    structure: str, paired: float = 35.0, unpaired: float = 25.0
) -> list[dict[str, object]]: ...
def dump_detections(
    structure: str, paired: float = 35.0, unpaired: float = 25.0, clearance: float = 1.0
) -> list[tuple[int, int, str]]: ...
def plot_coords_puzzler_resolver_off(structure: str) -> tuple[list[float], list[float]]: ...
