"""Type stub for the compiled `rna_draw._vienna_layout` pybind11 extension.

The extension itself is built by `src/vienna_layout/bindings.cpp`
(CMakeLists.txt) and installed alongside this package; it is not part of
the source tree, so mypy needs this stub to type-check callers.
"""

def version() -> str: ...
def abi_version() -> tuple[int, int, int]: ...
def sizeof_puzzler_options() -> int: ...
def plot_coords_puzzler(structure: str) -> tuple[list[float], list[float]]: ...
def plot_coords_puzzler_opts(
    structure: str, allow_flipping: bool = False, max_config_changes: int = 0
) -> tuple[list[float], list[float]]: ...
def plot_coords_naview(structure: str) -> tuple[list[float], list[float]]: ...
def plot_coords_turtle(structure: str) -> tuple[list[float], list[float]]: ...
